### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hugusmaximus**
Added instructions to build and run it on qemu so there's no need to have an Odroid-XU4 board.

### CODE REVIEW

**Comment by lsf37** [comment]
Since it's just adding a few instructions to an existing file, it's Ok to accept without the sign-off line.

**Review by axel-h — APPROVED** [review]
The documentation change look sane to me, but I have not tried them out practically. What is wonder about is when it says "Notice: currently you will have no network in qemu.". There could be a brief section about how one would test this practically now in QEMU then - but maybe that is obvious to somebody familiar with this example...?

**Comment by lsf37** [comment]
> There could be a brief section about how one would test this practically now in QEMU then - but maybe that is obvious to somebody familiar with this example...?

Good point. @kent-mcleod or @nomadeel do you know?

**Comment by olofholmberg** [comment]
I ran into the same issue when trying to run the webserver example (that no network is available inside the VM). So a section on how to successfully pass a network device to the vm would be nice to have. 

Through some digging in the mailing list i found a recommended way of passing ethernet to qemu: https://lists.sel4.systems/hyperkitty/list/devel@sel4.systems/message/X34TX7KA27EH3EWNKNVX5SUHKRDIAKLG/

And using the links I assumed this was the correct way of passing it to qemu: 
sudo ./simulate --extra-qemu-args="-netdev tap,id=mynet0,ifname=tap0,script=no,downscript=no -device virtio-net,netdev=mynet0,mac=52:55:00:d1:55:01"

However I was not able to find any device inside the VM that seemed to have a connection to the device passed to qemu.

You can see the full details of my own question regarding that issue here: https://lists.sel4.systems/hyperkitty/list/devel@sel4.systems/thread/KABQ6CD4SKQJR74RQ4AHIW47U6N5SQ7W/

**Comment by olofholmberg** [comment]
I managed to setup the network at least. I cannot verify that the webserver example works since the building of lighttpd seems to hang and never complete (don't know why at this moment). Thus, when testing this I commented out the build of lighttpd in CMakeLists.txt. But if someone wants to verify and add the instructions of setting up and making it work with the webserver this is how I did it:

Start qemu with the following command:
sudo ./simulate --extra-qemu-args="-netdev tap,id=mynet0,ifname=tap0,script=no,downscript=no -device virtio-net,netdev=mynet0,mac=52:55:00:d1:55:01,disable-modern=on,disable-legacy=off"

This thread that suggested adding ",disable-modern=on,disable-legacy=off" might be of interest when figuring out what was missing or went wrong in the example: https://qemu-devel.nongnu.narkive.com/otcGnLuw/bug-virtio-net-linux-driver-fails-to-probe-on-mips-malta-since-hw-virtio-pci-fix-virtio-behaviour

When the VM has booted, add an ip to the "eth0" device that should now be visible. Do this by editing the /etc/network/interfaces file and adding:

auto eth0
iface eth0 inet static
address 10.13.1.7
netmask 255.255.255.0

Then save the changes and run:

ifup eth0

I assume that this should be enough to access the webserver from the host by navigating to: 10.13.1.7:3000
If it does not work, try adding an ip to the device in the host (choose X to whatever number that is available):

sudo ip addr add 192.168.0.X/24 dev tap0
sudo ip link set dev tap0 up

And then try to debug the connections (ping from host to vm and from vm to host worked for me at least).

**Comment by hugusmaximus** [comment]
For me it's working perfectly with the Olof's last qemu command (sudo ./simulate --extra-qemu-args="-netdev tap,id=mynet0,ifname=tap0,script=no,downscript=no -device virtio-net,netdev=mynet0,mac=52:55:00:d1:55:01,disable-modern=on,disable-legacy=off"):
--------
Starting network: OK
[    6.431947] connection: loading out-of-tree module taints kernel.
[    6.469091] Event Bar (dev-0) initalised
[    6.492662] 2 Dataports (dev-0) initalised
udhcpc: started, v1.31.0
[   16.026150] random: mktemp: uninitialized urandom read (6 bytes read)
udhcpc: sending discover
udhcpc: sending select for 192.168.122.100
udhcpc: lease of 192.168.122.100 obtained, lease time 600
[   17.503524] random: mktemp: uninitialized urandom read (6 bytes read)
adding dns 8.8.8.8
adding dns 8.8.4.4

Welcome to Buildroot
buildroot login: root
# ifconfig 
eth0      Link encap:Ethernet  HWaddr 52:55:00:D1:55:01  
          inet addr:192.168.122.100  Bcast:192.168.122.255  Mask:255.255.255.0
          inet6 addr: fe80::5055:ff:fed1:5501/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:27 errors:0 dropped:14 overruns:0 frame:0
          TX packets:12 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2562 (2.5 KiB)  TX bytes:1736 (1.6 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

---
And I can reach the webserver from external network (from the host). Notice that before to run qemu I did some job on the host:

1) I set up a dnsserver (specifically this one: https://linuxmeditation.com/setting-up-dhcp-server-on-ubuntu-20-04/)
2) I creatred a bridge in my host (following those instructions: https://gist.github.com/extremecoders-re/e8fd8a67a515fee0c873dcafc81d811c)

Not sure if this second step is really necessary or I overkilled the solution... here is how my host network setup looks now:

hugo@dev:~/seL4/sel4webserver_hugusmaximus_fork/build$ brctl show
bridge name	bridge id		STP enabled	interfaces
virbr0		8000.52540008cac0	yes		eno1
							tap0
							virbr0-nic
hugo@dev:~/seL4/sel4webserver_hugusmaximus_fork/build$ ifconfig -a
eno1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 5c:26:0a:05:38:31  txqueuelen 1000  (Ethernet)
(...)
tap0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::50d8:59ff:fe02:c823  prefixlen 64  scopeid 0x20<link>
        ether 52:d8:59:02:c8:23  txqueuelen 1000  (Ethernet)
(...)
virbr0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
        ether 52:54:00:08:ca:c0  txqueuelen 1000  (Ethernet)
 (...)
virbr0-nic: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.10  netmask 255.255.255.0  broadcast 192.168.122.255
        ether 52:54:00:08:ca:c0  txqueuelen 1000  (Ethernet)
(...)

**Comment by kent-mcleod** [comment]
> Good point. @kent-mcleod or @nomadeel do you know?

Both @olofholmberg and @hugusmaximus suggestions should work well.  The lighttpd module installs a startup script into the guest that brings up eth0 and starts `udhcpc` to get an ip address from a dhcp server running on the host.  Using the bridge should make the guest visible to other machines that are on networks attached to the bridge.

If you just want to access the guest from the host only, then a bridge shouldn't be necessary:
`sudo ./simulate --extra-qemu-args="-netdev tap,id=mynet0,ifname=tap0 -device virtio-net,netdev=mynet0,mac=52:55:00:d1:55:01"` (The default qemu-if scripts should create a tap0 if one doesn't exist already).
Then you can assign a static IP for the host, and start a dhcp server in another terminal on the host (or write your own qemu-ifup script that qemu will call if you set it as the script argument):
```
sudo ip addr add 10.0.120.100/24 dev tap0
sudo udhcpd -f /etc/udhcpd.conf 
```
If you setup the guest to statically assign an IP like what @olofholmberg does, then you wouldn't need the dhcp server on the host.

**Comment by kent-mcleod** [comment]
> I managed to setup the network at least. I cannot verify that the webserver example works since the building of lighttpd seems to hang and never complete (don't know why at this moment).

@olofholmberg this could be because of other long running (or hung) build steps. I made a PR to try and get the ones I was aware of to run in the foreground so that you can see progress or prompts:   https://github.com/seL4/sel4webserver/pull/2

**Review by kent-mcleod — APPROVED** [review]

**Comment by hugusmaximus** [comment]
@kent-mcleod , regarding this: 

"The lighttpd module installs a startup script into the guest that brings up eth0 and starts udhcpc to get an ip address from a dhcp server running on the host."

I think this script should run udhcpc in background otherwise on some scenarios (in example when no network device is available) you get an unusable prompt with udhcpc trying to get an IP in an endless loop and there's no way to kill it from the console basically because console becomes unresponsive (at least this is my case). In other words, as the only prompt to the guest Linux is the console, I think we should be careful not to stuck it with any process. Just an idea to avoid future similar problems.

**Comment by hugusmaximus** [comment]
@kent-mcleod , your command  (sudo ./simulate --extra-qemu-args="-netdev tap,id=mynet0,ifname=tap0 -device virtio-net,netdev=mynet0,mac=52:55:00:d1:55:01") doesn't work on my tests and gives this error:

ifconfig: SIOCGIFFLAGS: No such device
udhcpc: SIOCGIFINDEX: No such device

Instead, Olof's command (sudo ./simulate --extra-qemu-args="-netdev tap,id=mynet0,ifname=tap0,script=no,downscript=no -device virtio-net,netdev=mynet0,mac=52:55:00:d1:55:01,disable-modern=on,disable-legacy=off") looks like works:

Starting network: OK
[    6.172036] connection: loading out-of-tree module taints kernel.
[    6.206878] Event Bar (dev-0) initalised
[    6.227940] 2 Dataports (dev-0) initalised
udhcpc: started, v1.31.0
[   15.623094] random: mktemp: uninitialized urandom read (6 bytes read)
udhcpc: sending discover

Thus I'm going to add this to another pull request with some suggestions about the two different approaches of "simulate" (with/without script) and two different approaches of network configuration: either to set up static IP (Olof's approach) either to set up dhcp server on the host (my approach). I also will add some instructions about creating a bridge as in my case with a default qemu installation, I don't get a tap0 interface created thus even host connectivity do not work. My idea is to just give some different options and some example but letting the reader notice that specific configuration commands may be different on every scenario/distro, etc. I think this may be enough information, or at least more than what we had before (I would had loved to have it).

Let me know your opinions about this.

**Comment by kent-mcleod** [comment]
> I think this script should run udhcpc in background otherwise on some scenarios (in example when no network device is available) you get an unusable prompt with udhcpc trying to get an IP in an endless loop and there's no way to kill it from the console basically because console becomes unresponsive (at least this is my case). In other words, as the only prompt to the guest Linux is the console, I think we should be careful not to stuck it with any process. Just an idea to avoid future similar problems.

Feel free to change this.  The way it was implemented initially was to make it easy to detect a successful boot in CI via simply looking for the console getting to the login prompt.

> @kent-mcleod , your command (sudo ./simulate --extra-qemu-args="-netdev tap,id=mynet0,ifname=tap0 -device virtio-net,netdev=mynet0,mac=52:55:00:d1:55:01") doesn't work on my tests and gives this error:

I checked again that the script works for my version: QEMU emulator version 5.2.0 (Debian 1:5.2+dfsg-3)
I do get the following warning though:
`W: /etc/qemu-ifup: no bridge for guest interface found`
I agree that explicitly setting up a bridge and tap device is more likely to work across multiple different distributions and is clearer for instructions.


> Let me know your opinions about this.

I think this is helpful

**Review by hugusmaximus — COMMENTED** [review]
Signed-off-by: Hugo <skydivebcn@gmail.com>

**Review by hugusmaximus — COMMENTED** [review]
Signed-off-by: Hugo <skydivebcn@gmail.com>

**Comment by hugusmaximus** [comment]
Done via web interface as via CLI is not working for me (my local branch is
not listed anymore). Let me know if it works like this or not, I didn't
find any option in the Git web interface to enable DCO so I just simply
added the "Sign-off" line to a review comment.

**Comment by lsf37** [comment]
The sign-off line has to be in the commit message for the check to recognise it, but I'm happy to take it as permission for one of us to sign off on your behalf.

**Pull request merged**
